version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: destinify_db
    restart: always
    environment:
      POSTGRES_USER: destinify_user
      POSTGRES_PASSWORD: destinify_password
      POSTGRES_DB: destinify_db
    ports:
      - "5437:5432"                       # Mapeo del puerto para acceder desde tu máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volumen para persistir los datos

volumes:
  postgres_data:
